// Generated by: npx supabase gen types typescript --project-id [ID] > src/types/database.ts
// Do not edit manually — regenerate when schema changes.

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
